### ISSUE TITLE
Push notifications and dimelo component as a fragment.

### ISSUE THREAD

**Issue by fdematos** [dimelo/Dimelo-Android#17]
Hi,

We are using your component as a fragment.
The problem is that in that case, when a user receive a Dimelo notification and tap on it, it does not open the component.

It works correctly as an activity but not as a fragment.

Can you allow the tap on a push notif to open the fragment the same way it does with an activity.

Thanks

**Comment by Cylix** [comment]
Hi,

This is indeed correct.
When we build the notification, we create a pendingIntent which opens the Dimelo `ChatActivity` and that has no support for fragments.

I definitely can add a support for fragments.
The way `PendingIntent` works, I have to pass in the activity that will load the chat fragment.
As we can't guess which activity of the host application is in charge of the fragment, I can simply provide you a way to specify us this activity.

For example, I can provide you an overload of the `consumeReceivedRemoteNotification` function: 

```java
public static boolean consumeReceivedRemoteNotification(@NonNull Context context, @NonNull Bundle payload, @Nullable NotificationDisplayer notifDisplayer, @Nullable ComponentName activity)
```

Would it be OK for you?

Moreover, if you later need to have more hands on the notification building process, you also have the ability to create your own NotificationDisplayer (3rd parameter of `consumeReceivedRemoteNotification`).

Best

**Comment by Cylix** [comment]
Ok, I just pushed a new version, 1.5.1.

Inside, there is a new consumeReceivedRemoteNotification overload with the following prototype:

```java
public static boolean consumeReceivedRemoteNotification(@NonNull Context context, @NonNull Bundle payload, @Nullable NotificationDisplayer notifDisplayer, @Nullable Class<?> activity);
```

You can basically pass the activity you want to launch when the notification is clicked, basically the activity that wraps the Dimelo fragment.

```java
.consumeReceivedRemoteNotification(context, payload, null, YourActivity.class);
```

For now, in order to only make this change a minor one without any breaking change, it is only applied when using our own default NotificationDisplayer.

Do not hesitate to give me feedbacks about this change: whether it solves your issue or not at all, or any other remarks.

Best.

**Comment by jfgrim** [comment]
It's ok for this dev ...
But I could add a new activity in consumeReceivedRemoteNotification (...), but this activity must have a parent declared.
I added the declaration in manifest, parentActivity for this new activity : 

        <activity
            android:name=".ui.chat.XxxChatActivity"
            android:parentActivityName=".ui.home.HomeActivity"
            android:screenOrientation="portrait" />
