### ISSUE TITLE
The number of unread messages is not set to zero

### ISSUE THREAD

**Issue by ghost** [dimelo/Dimelo-Android#19]
I'm using Dimelo SDK v.1.4.4. I'm displaying the chat as fragment. The problem is that when I receive message from support side, the number of unread messages is increased but never set to zero, even after repeated opening the chat. The method "getUnreadCount" and UnreadCountChangedCallback always return non-zero value. What could be the reason?

**Comment by jarthod** [comment]
Hello,

The unread messages count is updated periodically while the chat is open (every 5 sec) and when the chat is instantiated. So if you open and close the chat quickly it may not update the counter. Can you try waiting more than 5 seconds with the chat open to see if it works?

You say the count is never set to zero but does it decrements at some point? because if it does it means the update is working but some messages are still considered unread. If so, is the chat view properly scrolled to the bottom?

You can force and update by calling `setUserIdentifier()` as it forces an initialization call to the server which also updates the unread msg count, but this is not recommended.

**Comment by thedrugsthatdeceiveyou** [comment]
1. Yes, we tried to wait more then five seconds. The unread messages counter is only increase but never decrease.
2. We tried to scroll the chat to bottom but the counter hadn't decreased. 

Also we call the method setUserIdentifier() when receiving the chat token.
Is there any possibilities to decrease the counter?

**Comment by jarthod** [comment]
Ok, could you tell me if you:
- Receive 1 message (the count is updated to 1)
- Open the chat, send some replies and close (the count is still 1 in your case)
- Now if you receive, say 2 more messages, is the unread count incremented to 3 or 2?

Thanks.

**Comment by thedrugsthatdeceiveyou** [comment]
I did following steps:

1. Received 1 message (the counter was updated to 1)
2. Opened the chat, sent message, closed the chat (the counter was still 1)
3. Received 3 messages, the counter was updated to 4
4. Opened the chat, sent one more message, closed the chat, the counter = 4
5. Received one more message, the counter was updated to 5

**Comment by jarthod** [comment]
Ok this confirms your problem is with the mark as read feature, which means the SDK is not aware that the chat is being displayed, and thus the server is never notified the messages are read.

Could you show us the way you display the Chat?, you're most probably in the 3rd case of [Dimelo's documentation about displaying the chat](https://github.com/dimelo/Dimelo-Android#displaying-the-mobile-messaging) (Nested Fragment)

In which case did you properly use `Fragment.setUserVisibleHint` in order to notify the chat about its visibility state?

Thanks.

**Comment by thedrugsthatdeceiveyou** [comment]
The problem was that Fragment.setUserVisibleHint was used in wrig way, now it is fixed. So the chat works correctly, thanks

**Comment by jarthod** [comment]
Ok perfect ☺
