### ISSUE TITLE
404 Api request

### ISSUE THREAD

**Issue by Jjourde** [dimelo/Dimelo-Android#21]
Hello,

I note randomly bug on SDK and Dimelo API.
When user receive push notification, and he click on it, the chat history unload. In the application logs, Dimelo SDK throw a 404 request with the message ` {"error":"Unknown API key","localizedError":"Une erreur est survenue, veuillez réessayer plus tard."}"`.
We use the last version of the SDK.
We test on android 5.0, 6.0.1 and 7.0.

Can you help us?

Thanks.

**Comment by jarthod** [comment]
Hello,

This error "Unknown API key", if random, probably means that the chat wasn't properly initialized a thus tried to query the server without an API key. You need to make sure the SDK is initialized with the proper API key whenever the app resumes from a notification (see https://github.com/dimelo/Dimelo-Android#push-notifications)

As it's random, how frequently do you have this problem? do you have steps to reproduce it? or at least stats in which the problem seems to be more frequent to you?

**Comment by Jjourde** [comment]
Hello,

Thank you for your answer.
The SDK is correcty initialized because I receive notifications. But in few cases, the new notification unload history.
I can't get you a frequency or steps to reproduce it, because it's very random :).

Thanks.

**Comment by jarthod** [comment]
Ok thanks, yes I guess the chat is properly initialized when you start the app, but I was thinking more about what happen when the app is closed and the notification tapped, because it's not necessarily the same code path and it's frequent for users to miss this case.

The fact that it unloads history is coherent with the error you showed earlier, if there's no API key the chat won't be able to load the history and will display a blank screen. Can you confirm that if you kill the app and tap the notification, it works most of the time?

**Comment by Jjourde** [comment]
Thanks,
But I can't reproduce bug systematically, so I can't confirm you if I kill app, notifications works fine.

**Comment by jarthod** [comment]
Yes sure, I just wanted you to confirm that if you kill the app it works "most of the time", because if it works at least some times it probably means you're setting the API key properly in this code path.

**Comment by Jjourde** [comment]
Yes, if I killed the application and if I receive a new notification, it works "most of time".
I think the API key is set properly, because I can receive some notifications without problem.

**Comment by jarthod** [comment]
As seen with @DrissTM, the 404 was caused by a call to `setUserIdentifier` after `setJwt`, which actually clears the JWT (to avoid any conflict). We added a note to the readme about that: 198ba87575c3e5b166ab732b5694f78411b76860
