### ISSUE TITLE
Geolocation quitting without any user interaction and does'nt send location

### ISSUE THREAD

**Issue by karimkod** [dimelo/Dimelo-Android#39]
After I click on the location button it shows the map for seconds and then it quits and don't send the location infos in the chat.

**Comment by Bacdol** [comment]
Hi,

could you say us which version of our SDK do you use ?

Regards.

**Comment by karimkod** [comment]
Hi, 
we are using om.dimelo.dimelosdk:dimelosdk:1.6.4'

Thanks for answering

**Comment by Wacyp** [comment]
Hi, 

Could you please update your SDK to version 1.6.8 beforehand to check if posterior versions have corrected the behaviour you are observing ?

We checked to reproduce the behaviour that you are experiencing and this issue may come from your API Key considered not valid. You may still be using the default debug.keystore instead of generating and using a release one. 

If your app is not signed, the API Keys you use will be considered not valid by Google and prevent you from using them hence the observed behaviour (See https://developer.android.com/studio/publish/app-signing and https://developers.google.com/maps/documentation/android-sdk/signup?hl=fr ). 

Could you make sure that you are generating and using a release keystore and not the debug one in your APK app and come back to us whether it has resolved your issue or not ?

Best regards,

**Comment by karimkod** [comment]
Hi, 
I've tried all that you asked me to and the problem is always there.

Edit: Knowing that I have another usage of google maps API in my app and it works correctly.

Greetings.

**Comment by Wacyp** [comment]
Hi,

Could you please share your application logs when you try to open Maps via the Dimelo Mobile SDK ?

Best regards,

**Comment by Wacyp** [comment]
Hi @karimkod, did you manage to resolve your issue ?
